"use client";

import { AlertTriangle, Check, Cloud, CloudDownload, CloudUpload, LoaderCircle, LogIn, LogOut, Merge } from "lucide-react";
import { useState } from "react";
import type { useCloudAccount } from "@/hooks/use-cloud-account";

type CloudAccount = ReturnType<typeof useCloudAccount>;

export function CloudSync({ account, localCount, onNotify }: { account: CloudAccount; localCount: number; onNotify: (message: string) => void }) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [busy, setBusy] = useState(false);
  const runAuth = async (action: () => Promise<string | null>, success: string) => { setBusy(true); const error = await action(); setBusy(false); onNotify(error ?? success); };
  if (!account.configured) return <div className="cloud-card warning"><AlertTriangle size={20} /><div><strong>Account database is not configured</strong><p>Add the Supabase project URL and publishable key, then restart SubTrack.</p></div></div>;
  if (!account.user) return <div className="cloud-sync">
    <div className="cloud-card"><Cloud size={20} /><div><strong>Sign in to sync everywhere</strong><p>Your account database works across Wi-Fi and mobile networks. Signing in safely merges this device with your cloud account without replacing either collection.</p></div></div>
    <div className="settings-grid account-fields"><label className="field span-2"><span>Email</span><input type="email" autoComplete="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@example.com" /></label><label className="field span-2"><span>Password</span><input type="password" autoComplete="current-password" minLength={6} value={password} onChange={(event) => setPassword(event.target.value)} placeholder="At least 6 characters" /></label></div>
    <div className="data-actions auth-actions"><button className="button primary" disabled={busy || !email || password.length < 6} onClick={() => void runAuth(() => account.signIn(email, password), "Signed in.")}><LogIn size={16} /> Sign in</button><button className="button secondary" disabled={busy || !email || password.length < 6} onClick={() => void runAuth(() => account.signUp(email, password), "Account created. Check your email if confirmation is required.")}>Create account</button></div>
    <div className="data-actions auth-actions"><button className="button quiet" disabled={busy || !email} onClick={() => void runAuth(() => account.sendMagicLink(email), "Check your email for the sign-in link.")}>Email me a magic link</button></div>
  </div>;
  if (account.status === "setup-required") return <div className="cloud-sync"><div className="cloud-card warning"><AlertTriangle size={20} /><div><strong>Database setup required</strong><p>{account.errorMessage}</p></div></div><p className="section-copy account-help">Run <code>supabase/schema.sql</code> in this project’s Supabase SQL Editor, then reopen Settings.</p><button className="button secondary" onClick={() => void account.signOut()}><LogOut size={16} /> Sign out</button></div>;
  if (account.status === "choose" && account.migration) {
    const cloudCount = account.migration.cloud.subscriptions.length;
    return <div className="cloud-sync"><div className="cloud-card"><Cloud size={20} /><div><strong>Choose the first sync direction</strong><p>Signed in as {account.user.email}. Nothing moves until you choose.</p></div></div>
      <div className="migration-summary"><div><span>This device</span><strong>{localCount}</strong><small>subscriptions</small></div><div><span>Cloud account</span><strong>{cloudCount}</strong><small>subscriptions</small></div></div>
      {account.migration.cloudExists ? <div className="migration-actions"><button className="migration-choice recommended" onClick={() => void account.chooseCloud()}><CloudDownload size={19} /><span><strong>Download cloud data</strong><small>Recommended on a new phone. Replaces this device only after saving its local safety backup.</small></span></button><button className="migration-choice" onClick={() => void account.chooseMerge()}><Merge size={19} /><span><strong>Merge both collections</strong><small>Keeps unique subscriptions from both locations and resolves matching records by update time.</small></span></button><button className="migration-choice danger-choice" onClick={() => { if (confirm("Replace the cloud collection with this device’s data? A database history copy will be retained.")) void account.chooseLocal(); }}><CloudUpload size={19} /><span><strong>Replace cloud with this device</strong><small>Only use this when this device is definitely the correct source.</small></span></button></div> : <div className="migration-actions"><button className="migration-choice recommended" onClick={() => void account.chooseLocal()}><CloudUpload size={19} /><span><strong>Create cloud copy</strong><small>Upload this device’s {localCount} subscription{localCount === 1 ? "" : "s"} to the empty account.</small></span></button><button className="migration-choice" onClick={() => { if (!localCount || confirm("Start with an empty cloud account and clear this device’s current collection?")) void account.chooseCloud(); }}><CloudDownload size={19} /><span><strong>Start with empty account</strong><small>Leaves the cloud account empty and uses it on this device.</small></span></button></div>}
    </div>;
  }
  const syncing = account.status === "syncing" || account.status === "checking";
  return <div className="cloud-sync"><div className={`cloud-card ${account.status === "error" ? "warning" : ""}`}>{syncing ? <LoaderCircle className="spin" size={20} /> : account.status === "error" ? <AlertTriangle size={20} /> : <Check size={20} />}<div><strong>{syncing ? "Syncing account…" : account.status === "error" ? "Cloud sync needs attention" : `Synced as ${account.user.email}`}</strong><p>{account.errorMessage || (account.lastSyncedAt ? `Last synced ${new Intl.DateTimeFormat(undefined, { dateStyle: "medium", timeStyle: "short" }).format(new Date(account.lastSyncedAt))}.` : "Automatic cloud sync is active.")}</p></div></div><div className="data-actions"><button className="button primary" disabled={syncing} onClick={() => void account.syncNow()}><Cloud size={16} /> Sync now</button><button className="button secondary" onClick={() => void account.signOut()}><LogOut size={16} /> Sign out</button></div></div>;
}
